export const dummyData = [
    { Account_name: "Aarav Sharma", email: "aarav.sharma@example.com", phone: "9876543210", website: "aaravsharma.com", industry: "IT", Account_Status: "True", Remark: "Meeting scheduled" },
    { Account_name: "Ishita Verma", email: "ishita.verma@example.com", phone: "8765432109", website: "ishitaverma.com", industry: "Healthcare", Account_Status: "False", Remark: "Follow-up needed" },
    { Account_name: "Rajesh Gupta", email: "rajesh.gupta@example.com", phone: "7654321098", website: "rajeshgupta.com", industry: "Finance", Account_Status: "True", Remark: "Confirmed appointment" },
    { Account_name: "Pooja Iyer", email: "pooja.iyer@example.com", phone: "6543210987", website: "poojaiyer.com", industry: "Education", Account_Status: "False", Remark: "Pending response" },
    { Account_name: "Ankit Desai", email: "ankit.desai@example.com", phone: "5432109876", website: "ankitdesai.com", industry: "Retail", Account_Status: "True", Remark: "Interested" },
    { Account_name: "Neha Patil", email: "neha.patil@example.com", phone: "4321098765", website: "nehapatil.com", industry: "Hospitality", Account_Status: "True", Remark: "Inquiry received" },
    { Account_name: "Vikram Singh", email: "vikram.singh@example.com", phone: "3210987654", website: "vikramsingh.com", industry: "Real Estate", Account_Status: "False", Remark: "Needs clarification" },
    { Account_name: "Kavita Reddy", email: "kavita.reddy@example.com", phone: "2109876543", website: "kavitareddy.com", industry: "IT", Account_Status: "True", Remark: "Proposal sent" },
    { Account_name: "Arjun Kumar", email: "arjun.kumar@example.com", phone: "1098765432", website: "arjunkumar.com", industry: "Logistics", Account_Status: "False", Remark: "Pending approval" },
    { Account_name: "Meera Nair", email: "meera.nair@example.com", phone: "1987654321", website: "meeranair.com", industry: "E-commerce", Account_Status: "True", Remark: "Positive feedback" },
    { Account_name: "Sahil Chawla", email: "sahil.chawla@example.com", phone: "8765123490", website: "sahilchawla.com", industry: "Consulting", Account_Status: "True", Remark: "Meeting scheduled" },
    { Account_name: "Ritika Malhotra", email: "ritika.malhotra@example.com", phone: "7654012389", website: "ritikamalhotra.com", industry: "Healthcare", Account_Status: "False", Remark: "Awaiting response" },
    { Account_name: "Aditya Mehta", email: "aditya.mehta@example.com", phone: "6543021278", website: "adityamehta.com", industry: "Finance", Account_Status: "True", Remark: "Confirmed" },
    { Account_name: "Sneha Joshi", email: "sneha.joshi@example.com", phone: "5432130167", website: "snehajoshi.com", industry: "Education", Account_Status: "False", Remark: "Postponed" },
    { Account_name: "Rohan Pillai", email: "rohan.pillai@example.com", phone: "4321049056", website: "rohanpillai.com", industry: "IT", Account_Status: "True", Remark: "Interested" },
    { Account_name: "Ananya Ghosh", email: "ananya.ghosh@example.com", phone: "3210958945", website: "ananyaghosh.com", industry: "Retail", Account_Status: "False", Remark: "Under review" },
    { Account_name: "Manish Dubey", email: "manish.dubey@example.com", phone: "2109867834", website: "manishdubey.com", industry: "Real Estate", Account_Status: "True", Remark: "Follow-up required" },
    { Account_name: "Priya Kapoor", email: "priya.kapoor@example.com", phone: "1098776723", website: "priyakapoor.com", industry: "Hospitality", Account_Status: "True", Remark: "Initial contact made" },
    { Account_name: "Kabir Chaudhary", email: "kabir.chaudhary@example.com", phone: "9877665612", website: "kabirchaudhary.com", industry: "Consulting", Account_Status: "False", Remark: "Details shared" },
    { Account_name: "Aditi Sharma", email: "aditi.sharma@example.com", phone: "8766554501", website: "aditisharma.com", industry: "E-commerce", Account_Status: "True", Remark: "Awaiting follow-up" },
    { Account_name: "Harsh Jain", email: "harsh.jain@example.com", phone: "7655443890", website: "harshjain.com", industry: "Healthcare", Account_Status: "False", Remark: "Pending" },
    { Account_name: "Tanya Singh", email: "tanya.singh@example.com", phone: "6544332789", website: "tanyasingh.com", industry: "Education", Account_Status: "True", Remark: "Meeting scheduled" },
    { Account_name: "Ajay Bhardwaj", email: "ajay.bhardwaj@example.com", phone: "5433221678", website: "ajaybhardwaj.com", industry: "Retail", Account_Status: "False", Remark: "Pending approval" },
    { Account_name: "Divya Menon", email: "divya.menon@example.com", phone: "4322110567", website: "divyamenon.com", industry: "Real Estate", Account_Status: "True", Remark: "Proposal accepted" },
    { Account_name: "Arvind Prasad", email: "arvind.prasad@example.com", phone: "3211009456", website: "arvindprasad.com", industry: "Finance", Account_Status: "True", Remark: "Details verified" },
    { Account_name: "Nisha Yadav", email: "nisha.yadav@example.com", phone: "2109998345", website: "nishayadav.com", industry: "IT", Account_Status: "True", Remark: "Inquiry received" },
    { Account_name: "Suresh Rao", email: "suresh.rao@example.com", phone: "1098887234", website: "sureshrao.com", industry: "Consulting", Account_Status: "False", Remark: "Follow-up needed" },
    { Account_name: "Rani Shekhar", email: "rani.shekhar@example.com", phone: "9877776123", website: "ranishekhar.com", industry: "E-commerce", Account_Status: "True", Remark: "Positive feedback" },
    { Account_name: "Kunal Agarwal", email: "kunal.agarwal@example.com", phone: "8766665012", website: "kunalagarwal.com", industry: "Hospitality", Account_Status: "True", Remark: "Confirmed" },
  ];
  